#!/usr/bin/env bash
# credentials/service.sh — manage credentials for any service in one script
# Usage: bash service.sh <service> <add|update|delete|list|verify>
#
# Supported services: confluence | jira | apidog
set -euo pipefail
source "$(dirname "$0")/_store.sh"

CONFIG_FILE="$HOME/.agent-skills-setup/config.sh"

# ---------------------------------------------------------------------------
# Service definitions
# ---------------------------------------------------------------------------
# Each service: <slug-prefix>|<url-prompt>|<config-host-key>|<config-user-key>|<extra-prompts>
#   url-prompt = empty if service has no URL (e.g. apidog)
#   extra-prompts = colon-separated list of "config_key:prompt_text" pairs
service_def() {
  case "$1" in
    confluence)
      echo "confluence|Confluence URL (e.g. https://confluence.example.com)|CONFLUENCE_HOST|CONFLUENCE_USER|"
      ;;
    jira)
      echo "jira|Jira URL (e.g. https://your-org.atlassian.net)|JIRA_HOST|JIRA_USER|JIRA_PROJECT_KEY:Jira project key (e.g. VOR)"
      ;;
    apidog)
      echo "apidog||APIDOG_HOST|APIDOG_USER|"
      ;;
    *)
      echo "ERROR: unknown service '$1'. Supported: confluence | jira | apidog" >&2
      return 1
      ;;
  esac
}

# ---------------------------------------------------------------------------
# write_config_kv <key> <value>
#   Idempotent upsert: replaces existing KEY=... line, or appends.
# ---------------------------------------------------------------------------
write_config_kv() {
  local key="$1" val="$2"
  mkdir -p "$(dirname "$CONFIG_FILE")"
  if [[ ! -f "$CONFIG_FILE" ]]; then
    {
      echo "# ~/.agent-skills-setup/config.sh — generated by setup-credentials.sh"
      echo "# Edit by hand if needed; setup-credentials re-reads on next run."
      echo ""
    } > "$CONFIG_FILE"
  fi
  if grep -q "^$key=" "$CONFIG_FILE" 2>/dev/null; then
    sed -i.bak "s|^$key=.*|$key=\"$val\"|" "$CONFIG_FILE"
    rm -f "$CONFIG_FILE.bak"
  else
    echo "$key=\"$val\"" >> "$CONFIG_FILE"
  fi
}

# ---------------------------------------------------------------------------
# read_config_kv <key>
#   Print value of $key from config.sh, empty if missing.
# ---------------------------------------------------------------------------
read_config_kv() {
  [[ -f "$CONFIG_FILE" ]] || { echo ""; return; }
  local val
  val=$(grep "^$1=" "$CONFIG_FILE" 2>/dev/null | head -1 | sed 's/^[^=]*=//;s/^"//;s/"$//')
  echo "$val"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
SERVICE="${1:-}"
ACTION="${2:-}"

if [[ -z "$SERVICE" || -z "$ACTION" ]]; then
  echo "Usage: $0 <service> <add|update|delete|list|verify>"
  echo "Services: confluence | jira | apidog"
  exit 1
fi

DEF=$(service_def "$SERVICE") || exit 1
IFS='|' read -r SLUG_PREFIX URL_PROMPT HOST_KEY USER_KEY EXTRA <<< "$DEF"

# ---------------------------------------------------------------------------
# Compute slug from current host (URL or fixed for apidog)
# Reads HOST from config.sh first; prompts if missing.
# ---------------------------------------------------------------------------
compute_slug() {
  if [[ -z "$URL_PROMPT" ]]; then
    echo "$SLUG_PREFIX"
    return
  fi
  local host
  host=$(read_config_kv "$HOST_KEY")
  if [[ -z "$host" ]]; then
    echo "ERROR: $HOST_KEY not in config.sh — run '$0 $SERVICE add' first." >&2
    return 1
  fi
  source "$HOME/.agent-skills-setup/lib.sh" 2>/dev/null
  service_slug "$SLUG_PREFIX" "https://$host"
}

case "$ACTION" in
  add|update)
    if [[ -n "$URL_PROMPT" ]]; then
      DEFAULT_HOST=$(read_config_kv "$HOST_KEY")
      read -rp "$URL_PROMPT${DEFAULT_HOST:+ [https://$DEFAULT_HOST]}: " URL_INPUT
      URL_INPUT="${URL_INPUT:-https://$DEFAULT_HOST}"
      HOST_VALUE="${URL_INPUT#https://}"; HOST_VALUE="${HOST_VALUE#http://}"
      write_config_kv "$HOST_KEY" "$HOST_VALUE"
      SLUG="${SLUG_PREFIX}-$(echo "$URL_INPUT" | sed 's|[^a-zA-Z0-9]|-|g;s/-\+/-/g;s/-$//')"
    else
      SLUG="$SLUG_PREFIX"
    fi

    DEFAULT_USER=$(read_config_kv "$USER_KEY")
    read -rp "Username${DEFAULT_USER:+ [$DEFAULT_USER]}: " USER_INPUT
    USER_INPUT="${USER_INPUT:-$DEFAULT_USER}"
    write_config_kv "$USER_KEY" "$USER_INPUT"

    read -rsp "Password / API token (hidden): " PASS; echo
    store_credential "$SLUG" "$USER_INPUT" "$PASS"

    if [[ -n "$EXTRA" ]]; then
      IFS=':' read -r EXTRA_KEY EXTRA_PROMPT <<< "$EXTRA"
      DEFAULT_EXTRA=$(read_config_kv "$EXTRA_KEY")
      read -rp "$EXTRA_PROMPT${DEFAULT_EXTRA:+ [$DEFAULT_EXTRA]}: " EXTRA_INPUT
      EXTRA_INPUT="${EXTRA_INPUT:-$DEFAULT_EXTRA}"
      write_config_kv "$EXTRA_KEY" "$EXTRA_INPUT"
    fi

    echo "  ✓ $SERVICE credentials saved (keychain + $CONFIG_FILE)"
    ;;

  delete)
    SLUG=$(compute_slug) || exit 1
    USER_VAL=$(read_config_kv "$USER_KEY")
    if [[ -z "$USER_VAL" ]]; then
      read -rp "Username: " USER_VAL
    fi
    delete_credential "$SLUG" "$USER_VAL"
    ;;

  list)
    list_credentials
    ;;

  verify)
    SLUG=$(compute_slug) || exit 1
    USER_VAL=$(read_config_kv "$USER_KEY")
    if [[ -z "$USER_VAL" ]]; then
      read -rp "Username: " USER_VAL
    fi
    verify_credential "$SLUG" "$USER_VAL"
    ;;

  *)
    echo "Unknown action: $ACTION. Use add|update|delete|list|verify." >&2
    exit 1
    ;;
esac
